name: restricted_products
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.1.0
  - absl-py=0.7.1
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - astor=0.7.1
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - automat=0.7.0
  - backcall=0.1.0
  - bcrypt=3.1.6
  - blas=1.0
  - bleach=3.1.0
  - bokeh=1.2.0
  - c-ares=1.15.0
  - ca-certificates=2019.6.16
  - certifi=2019.6.16
  - cffi=1.12.3
  - constantly=15.1.0
  - cryptography=2.7
  - cssselect=1.0.3
  - cudatoolkit=10.0.130
  - cudnn=7.6.0
  - cupti=10.0.130
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gast=0.2.2
  - glib=2.56.2
  - gmp=6.1.2
  - grpcio=1.16.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.9.0
  - hdf5=1.10.4
  - hyperlink=19.0.0
  - icu=58.2
  - idna=2.8
  - importlib_metadata=0.17
  - incremental=17.5.0
  - intel-openmp=2019.4
  - ipykernel=5.1.1
  - ipython=7.6.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.3
  - jinja2=2.10.1
  - joblib=0.13.2
  - jpeg=9b
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - keras-applications=1.0.8
  - keras-base=2.2.4
  - keras-gpu=2.2.4
  - keras-preprocessing=1.1.0
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.8.0
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - libxslt=1.1.33
  - lxml=4.3.4
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.0
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - mock=3.0.5
  - more-itertools=7.0.0
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.7.8
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - openssl=1.1.1c
  - packaging=19.0
  - pandas=0.24.2
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parsel=1.5.1
  - parso=0.5.0
  - patsy=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.0.0
  - pip=19.1.1
  - pluggy=0.12.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - protobuf=3.8.0
  - ptyprocess=0.6.0
  - py=1.8.0
  - pyasn1=0.4.5
  - pyasn1-modules=0.2.4
  - pycparser=2.19
  - pydispatcher=2.0.5
  - pygments=2.4.2
  - pyhamcrest=1.9.0
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - pytest=5.0.0
  - pytest-runner=4.4
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyyaml=5.1.1
  - pyzmq=18.0.0
  - qt=5.9.7
  - qtconsole=4.5.1
  - queuelib=1.5.0
  - readline=7.0
  - scikit-learn=0.21.2
  - scipy=1.2.1
  - scrapy=1.6.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - service_identity=18.1.0
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.28.0
  - statsmodels=0.10.0
  - tensorboard=1.13.1
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0
  - tensorflow-gpu=1.13.1
  - tensorflow-hub=0.6.0
  - termcolor=1.1.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=6.0.3
  - tqdm=4.35.0
  - traitlets=4.3.2
  - twisted=19.2.0
  - w3lib=1.20.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.15.4
  - wheel=0.33.4
  - widgetsnbextension=3.4.2
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zipp=0.5.1
  - zlib=1.2.11
  - zope=1.0
  - zope.interface=4.6.0
  - zstd=1.3.7
  - pip:
    - bert-tensorflow==1.0.1
    - import-ipynb==0.1.3
    - jupyterthemes==0.20.0
    - lesscpy==0.13.0
    - ply==3.11
    - unidecode==1.1.1

